//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBRN
    {
        public string strURN { get; set; }
        public string strCountryOrigin { get; set; }
        public string strType { get; set; }
        public string strQuantityMeasurement { get; set; }
        public string strMethodDelivery { get; set; }
        public string strManufacturer { get; set; }
        public string strCountryRecovered { get; set; }
        public string strUNNumber { get; set; }
        public string strSpecialPrecautions { get; set; }
        public string strOther { get; set; }
        public string strSecurityRating { get; set; }
        public int intID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string textSearch { get; set; }
        public string strHazard { get; set; }
        public string strName { get; set; }
        public string strPrimaryMediaImageUrn { get; set; }
        public Nullable<int> intQuantity { get; set; }
        public string memRemarks { get; set; }
        public string strCategory { get; set; }
        public string strDescription { get; set; }
    }
}
