//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chemical
    {
        public string strURN { get; set; }
        public string Name { get; set; }
        public string OtherNames { get; set; }
        public string CountryRecovered { get; set; }
        public string CountryOrigin { get; set; }
        public string CasNo { get; set; }
        public string RtecsNo { get; set; }
        public string UnNo { get; set; }
        public string EcNo { get; set; }
        public string ChemicalFormula { get; set; }
        public string PhysicalAppearance { get; set; }
        public string ChemicalDangers { get; set; }
        public string OccupationalExposureLimitsTLV { get; set; }
        public string OccupationalExposureLimitsMAK { get; set; }
        public string RoutesOfExposure { get; set; }
        public string SpillageDisposal { get; set; }
        public string Packaging { get; set; }
        public string Labelling { get; set; }
        public string SafeStorage { get; set; }
        public string TransportEmergencyCard { get; set; }
        public string NfpaCode { get; set; }
        public string UnHazardClass { get; set; }
        public string UnSubsidiaryRisks { get; set; }
        public string UnPackGroup { get; set; }
        public string HazardExposure { get; set; }
        public Nullable<float> BoilingPointLow { get; set; }
        public Nullable<float> BoilingPointHigh { get; set; }
        public Nullable<float> MeltingPointHighLow { get; set; }
        public Nullable<float> MeltingPointHigh { get; set; }
        public Nullable<float> DensityLow { get; set; }
        public Nullable<float> DensityHigh { get; set; }
        public Nullable<float> RelativeDensityLow { get; set; }
        public Nullable<float> RelativeDensityHigh { get; set; }
        public string WaterSolubility { get; set; }
        public Nullable<float> VapourPressureLow { get; set; }
        public Nullable<float> VapourPressureHigh { get; set; }
        public Nullable<float> RelativeVapourDensityLow { get; set; }
        public Nullable<float> RelativeVapourDensityHigh { get; set; }
        public Nullable<float> FlashPointLow { get; set; }
        public Nullable<float> FlashPointHigh { get; set; }
        public Nullable<float> AutoIgnitionTempLow { get; set; }
        public Nullable<float> AutoIgnitionTempHigh { get; set; }
        public string ExplosiveLimits { get; set; }
        public Nullable<float> OctanolWaterPartitionLow { get; set; }
        public Nullable<float> OctanolWaterPartitionHigh { get; set; }
        public string InhalationRisk { get; set; }
        public string EnvironmentalData { get; set; }
        public string memRemarks { get; set; }
        public Nullable<System.DateTime> dteSent { get; set; }
        public int intID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string textSearch { get; set; }
    }
}
