//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Communication
    {
        public string strURN { get; set; }
        public string CommType { get; set; }
        public string CommDescription { get; set; }
        public string CommName { get; set; }
        public string Other { get; set; }
        public string WebValue { get; set; }
        public string Number { get; set; }
        public string ServiceProvider { get; set; }
        public string CountryOrigin { get; set; }
        public string memRemarks { get; set; }
        public Nullable<System.DateTime> dteSent { get; set; }
        public int intID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string textSearch { get; set; }
    }
}
