//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public string strURN { get; set; }
        public string Type { get; set; }
        public string CountryOrigin { get; set; }
        public string Material { get; set; }
        public string Manufacturer { get; set; }
        public string Description { get; set; }
        public string MethodDelivery { get; set; }
        public Nullable<float> QuantityWeight { get; set; }
        public Nullable<float> QuantityNo { get; set; }
        public string CountryRecovered { get; set; }
        public Nullable<float> Length { get; set; }
        public Nullable<float> Width { get; set; }
        public Nullable<float> Height { get; set; }
        public Nullable<float> Diameter { get; set; }
        public string Colour { get; set; }
        public string Markings { get; set; }
        public string memRemarks { get; set; }
        public Nullable<System.DateTime> dteSent { get; set; }
        public int intID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string textSearch { get; set; }
    }
}
