//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseList
    {
        public string strURN { get; set; }
        public Nullable<int> intType { get; set; }
        public string strTitle { get; set; }
        public string strTable { get; set; }
        public string strTranslation { get; set; }
        public Nullable<bool> optTransmit { get; set; }
        public bool optPhysicalDatabase { get; set; }
        public Nullable<System.DateTime> dteSent { get; set; }
        public int intID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string textSearch { get; set; }
        public string strControllerName { get; set; }
    }
}
