//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Explosive
    {
        public string strURN { get; set; }
        public string Category { get; set; }
        public string Type { get; set; }
        public Nullable<float> Quantity { get; set; }
        public string MeasurementUnit { get; set; }
        public string BrandName { get; set; }
        public string Manufacturer { get; set; }
        public string CountryOrigin { get; set; }
        public string CountryRecovered { get; set; }
        public string Markings { get; set; }
        public string Colour { get; set; }
        public string Packaging { get; set; }
        public Nullable<float> ExplosiveLength { get; set; }
        public Nullable<float> ExplosiveWidth { get; set; }
        public Nullable<float> ExplosiveHeight { get; set; }
        public Nullable<float> ExplosiveWeight { get; set; }
        public Nullable<float> ExplosiveDiameter { get; set; }
        public string memRemarks { get; set; }
        public Nullable<System.DateTime> dteSent { get; set; }
        public int intID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string textSearch { get; set; }
    }
}
