//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firearm
    {
        public string strURN { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public Nullable<bool> Logo { get; set; }
        public string CountryOrigin { get; set; }
        public string Impoter { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<bool> SerialErased { get; set; }
        public string Type { get; set; }
        public string Action { get; set; }
        public string Calibre { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string CountryRecovered { get; set; }
        public Nullable<float> BarrelLength { get; set; }
        public Nullable<int> RoundsHeld { get; set; }
        public Nullable<bool> Deactivated { get; set; }
        public Nullable<bool> Reactivated { get; set; }
        public Nullable<bool> FactoryMade { get; set; }
        public Nullable<bool> Imitation { get; set; }
        public string OwnersCertificateNumber { get; set; }
        public string memRemarks { get; set; }
        public Nullable<System.DateTime> dteSent { get; set; }
        public int intID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string textSearch { get; set; }
    }
}
