//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public string strURN { get; set; }
        public string GroupName { get; set; }
        public string SubCategory { get; set; }
        public string CountryOrigin { get; set; }
        public string GroupTo { get; set; }
        public string HeadName { get; set; }
        public string MemGoals { get; set; }
        public string strDeclaredByWhom { get; set; }
        public string Strength { get; set; }
        public string Area { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string PostalZip { get; set; }
        public string Address { get; set; }
        public string MemRemarks { get; set; }
        public Nullable<System.DateTime> DateEstablished { get; set; }
        public int intID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string textSearch { get; set; }
        public string GroupReportingAgency { get; set; }
    }
}
