//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordnance
    {
        public string strURN { get; set; }
        public string Category { get; set; }
        public string Type { get; set; }
        public string Other { get; set; }
        public string Manufacturer { get; set; }
        public string BrandName { get; set; }
        public string CountryRecovered { get; set; }
        public string CountryOrigin { get; set; }
        public Nullable<float> ExplosiveWeight { get; set; }
        public string memMarkings { get; set; }
        public string BatchCode { get; set; }
        public string SerialNumbers { get; set; }
        public string Colour { get; set; }
        public Nullable<float> Calibre { get; set; }
        public Nullable<bool> HeadStamp { get; set; }
        public Nullable<float> Length { get; set; }
        public Nullable<float> Width { get; set; }
        public Nullable<float> Depth { get; set; }
        public Nullable<float> Diameter { get; set; }
        public Nullable<float> NumberRecovered { get; set; }
        public string Remarks { get; set; }
        public int intID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string textSearch { get; set; }
    }
}
