//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.PersonAddresses = new HashSet<PersonAddress>();
            this.PersonPassportNoes = new HashSet<PersonPassportNo>();
            this.SocialMedias = new HashSet<SocialMedia>();
        }
    
        public string strURN { get; set; }
        public string Category { get; set; }
        public string CurrentStatus { get; set; }
        public string ReportingAgency { get; set; }
        public Nullable<int> NHeadMoney { get; set; }
        public string AccusationStatus { get; set; }
        public string Name { get; set; }
        public string Aliases { get; set; }
        public string FatherName { get; set; }
        public string FamilyName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PlaceOfBirth { get; set; }
        public string Tribe { get; set; }
        public Nullable<long> CNIC { get; set; }
        public string MaritalStatus { get; set; }
        public string Religion { get; set; }
        public string Occupation { get; set; }
        public string Education { get; set; }
        public string Email { get; set; }
        public string NormalDress { get; set; }
        public string BodyStructure { get; set; }
        public string BodyBuild { get; set; }
        public string BeardColor { get; set; }
        public string BaldType { get; set; }
        public string Height { get; set; }
        public string HeightInFeet { get; set; }
        public string Complexion { get; set; }
        public string IdentificationMark { get; set; }
        public string PermanentIdentificationMark { get; set; }
        public string DistinguishingMarks { get; set; }
        public string CovertAppearance { get; set; }
        public string OvertAppearance { get; set; }
        public string TalkingStyle { get; set; }
        public string VoicePitch { get; set; }
        public string HairCutStyle { get; set; }
        public string HairType { get; set; }
        public string HairColor { get; set; }
        public bool HairImplants { get; set; }
        public bool Wig { get; set; }
        public string CheekStructure { get; set; }
        public Nullable<bool> ContactLenses { get; set; }
        public string VFaceShape { get; set; }
        public string EarStructure { get; set; }
        public string EyeColor { get; set; }
        public string EyeLook { get; set; }
        public string Eyebrows { get; set; }
        public Nullable<bool> EyeGlasses { get; set; }
        public string NoseStructure { get; set; }
        public string LipStucture { get; set; }
        public string Mustaches { get; set; }
        public string MustachesColor { get; set; }
        public string memRemarks { get; set; }
        public int intID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string textSearch { get; set; }
        public bool iSHeadMoney { get; set; }
        public bool isActive { get; set; }
        public string FirNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonAddress> PersonAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonPassportNo> PersonPassportNoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialMedia> SocialMedias { get; set; }
    }
}
