//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pipe
    {
        public string strURN { get; set; }
        public string Category { get; set; }
        public string Type { get; set; }
        public string Other { get; set; }
        public string Manufacturer { get; set; }
        public string BrandName { get; set; }
        public string strCountryRecovered { get; set; }
        public string strCountryOrigin { get; set; }
        public Nullable<float> ExplosiveWeight { get; set; }
        public string memMarkings { get; set; }
        public string BatchCode { get; set; }
        public Nullable<float> Components { get; set; }
        public string ECMaterial { get; set; }
        public string ECManufacturer { get; set; }
        public string ECCountryOrigin { get; set; }
        public Nullable<float> ECLength { get; set; }
        public Nullable<float> ECDiameter { get; set; }
        public Nullable<float> ECMarkings { get; set; }
        public Nullable<float> ECQuantity { get; set; }
        public string MemRemarks { get; set; }
        public int intID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string textSearch { get; set; }
    }
}
