//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIncident
    {
        public int intID { get; set; }
        public string strURN { get; set; }
        public string strOperationName { get; set; }
        public Nullable<System.DateTime> dteIncidentDate { get; set; }
        public Nullable<System.DateTime> dteIncidentTime { get; set; }
        public Nullable<System.DateTime> dteIncidentTimeEnd { get; set; }
        public string strAddress { get; set; }
        public string strCityTownProvince { get; set; }
        public string strCountyState { get; set; }
        public string strPostalZip { get; set; }
        public string strCommonwealthTerritory { get; set; }
        public string strCountry { get; set; }
        public Nullable<double> intLatitude { get; set; }
        public Nullable<double> intLongitude { get; set; }
        public string strCaseFileRefNumber { get; set; }
        public string strDeliveryMethod { get; set; }
        public string strTarget { get; set; }
        public string strMotive { get; set; }
        public string strIncidentCategory { get; set; }
        public string strOther { get; set; }
        public Nullable<bool> optRecovered { get; set; }
        public string strPreIncidentThreat { get; set; }
        public string strPostIncidentThreat { get; set; }
        public Nullable<int> intNumberKilled { get; set; }
        public Nullable<int> intNumberInjured { get; set; }
        public Nullable<int> intNumberArrested { get; set; }
        public string strPrimaryMediaImageUrn { get; set; }
        public string strLegacyCode { get; set; }
        public Nullable<System.DateTime> dteIncidentDateWeekStart { get; set; }
        public Nullable<System.DateTime> dteIncidentDateWeekEnd { get; set; }
        public Nullable<int> intIncidentDay { get; set; }
        public string strDistrict { get; set; }
        public string strTargettedPersons { get; set; }
        public string strLatestCaseProgress { get; set; }
        public string strAdditionalRemarks { get; set; }
        public string strFirNo { get; set; }
        public string strCasualtiesNames { get; set; }
        public string strInjuredNames { get; set; }
        public string strRoleOfSig { get; set; }
        public Nullable<int> intIncidentMonth { get; set; }
        public Nullable<int> intIncidentYear { get; set; }
        public string strTargetDescription { get; set; }
        public string strSubTargetName { get; set; }
        public string strWeaponName { get; set; }
        public string strMotiveDescription { get; set; }
        public Nullable<int> intSubTarget { get; set; }
        public Nullable<int> intSuicideBorne { get; set; }
        public string strCaseStatus { get; set; }
        public string strMilitaryWeaponType { get; set; }
        public string strTimeZone { get; set; }
        public Nullable<int> intTimeOffset { get; set; }
        public Nullable<bool> optLibrary { get; set; }
        public Nullable<bool> optTransmit { get; set; }
        public string memRemarks { get; set; }
        public string excl_memTextSearch { get; set; }
        public Nullable<bool> optCompliance { get; set; }
        public string strSecurityRating { get; set; }
        public string strCreatedBy { get; set; }
        public Nullable<System.DateTime> dteCreated { get; set; }
        public Nullable<System.DateTime> dteSent { get; set; }
        public Nullable<System.DateTime> dteLastModified { get; set; }
        public string strLastModifiedBy { get; set; }
        public Nullable<bool> optSuicideBorne { get; set; }
        public string memRecoveries { get; set; }
    }
}
